version: 2
project_name: miru

before:
  hooks:
    - go mod tidy

builds:
  - id: miru
    main: ./cmd/miru
    binary: miru
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/hir4ta/miru/internal/installer.Version={{ .Version }}

archives:
  - id: default
    name_template: "miru_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - sample.md
      - sample.js
      - sample.py
      - sample.go
      - sample.json
      - LICENSE*

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

release:
  github:
    owner: hir4ta
    name: miru
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
